# Generated by Django 6.0.7 on 2026-09-15 11:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.CharField(max_length=64)),
                ('topic', models.CharField(max_length=100)),
                ('partition', models.IntegerField(blank=True, null=True)),
                ('offset', models.BigIntegerField(blank=True, null=True)),
                ('event_id', models.CharField(blank=True, max_length=64)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('raw', models.TextField()),
                ('error', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='correlation_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='next_retry_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['status', 'next_retry_at'], name='utils_outbo_status_43c8f7_idx'),
        ),
    ]
