"""
Django settings for conf project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from datetime import timedelta
from importlib.util import find_spec
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env(name: str, default: str = "") -> str:
    """Muhit o'zgaruvchisi, bo'lmasa default.

    Maxfiy qiymatlar (parol, kalit) HECH QACHON kodda turmasligi kerak —
    ular Kubernetes Secret'idan muhit o'zgaruvchisi sifatida keladi
    (k8s/booking-service.yaml dagi `envFrom.secretRef` shu uchun).
    Bu yerdagi default'lar faqat lokal ishlab chiqish uchun.
    """
    return os.environ.get(name, default)


# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  DEBUG / SECRET_KEY / ALLOWED_HOSTS — muhitdan.                          ║
# ║                                                                          ║
# ║  Lokalda hech narsa berish shart emas (DJANGO_DEBUG default "1").        ║
# ║  Prodda DJANGO_DEBUG=0 qo'yiladi va shu zahoti quyidagilar MAJBURIY      ║
# ║  bo'ladi: DJANGO_SECRET_KEY, DJANGO_ALLOWED_HOSTS, POSTGRES_DB,           ║
# ║  REDIS_URL, PAYME_SECRET_KEY. Birortasi yo'q bo'lsa Django ishga         ║
# ║  TUSHMAYDI — jimgina SQLite/LocMemCache/dev-kalit bilan ishlab ketgandan  ║
# ║  ko'ra erta va shovqinli yiqilish yaxshiroq.                             ║
# ╚══════════════════════════════════════════════════════════════════════════╝
DEBUG = env('DJANGO_DEBUG', '1').lower() in ('1', 'true', 'yes')

# Dev kaliti faqat DEBUG rejimida ishlatiladi (pastdagi _require_in_prod)
SECRET_KEY = env('DJANGO_SECRET_KEY') or 'django-insecure-dev-only-key-do-not-use-in-prod'

ALLOWED_HOSTS = [h.strip() for h in env('DJANGO_ALLOWED_HOSTS').split(',') if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']


def _require_in_prod(*names: str) -> None:
    missing = [n for n in names if not env(n)]
    if not DEBUG and missing:
        raise ImproperlyConfigured(
            f"Prod rejimida (DJANGO_DEBUG=0) majburiy: {', '.join(missing)}"
        )


_require_in_prod('DJANGO_SECRET_KEY', 'DJANGO_ALLOWED_HOSTS', 'POSTGRES_DB', 'REDIS_URL', 'ANALYTICS_SALT')

# A10: analitikadagi `client_hash` kaliti. O'zgartirilsa eski kohortalar uziladi.
ANALYTICS_SALT = env('ANALYTICS_SALT', 'dev-only-analytics-salt')

# A10: saqlash muddatlari (kun). `manage.py purge_expired_data` (kuniga bir marta cron).
# Buxgalteriya yozuvlari (Payment, Ledger) bu yerda YO'Q — ular qonuniy muddatgacha qoladi.
DATA_RETENTION = {
    'otp_codes_days': int(env('RETENTION_OTP_DAYS', '7')),
    'sms_log_days': int(env('RETENTION_SMS_LOG_DAYS', '90')),
    'outbox_published_days': int(env('RETENTION_OUTBOX_DAYS', '7')),
    'processed_events_days': int(env('RETENTION_PROCESSED_EVENTS_DAYS', '30')),
    'payme_callback_log_days': int(env('RETENTION_PAYME_LOG_DAYS', '365')),
    'audit_log_days': int(env('RETENTION_AUDIT_DAYS', str(5 * 365))),
    # E14: eng tez o'sadigan jadval. Bronga bog'lanmagan O'TGAN slotlar —
    # generatsiya qoldig'i, hech kimga kerak emas. Bronli slot o'chirilmaydi.
    'time_slots_days': int(env('RETENTION_TIME_SLOTS_DAYS', '90')),
    # C10: yopilgan navbat yozuvlari (kutayotganlar tegilmaydi)
    'waitlist_days': int(env('RETENTION_WAITLIST_DAYS', '90')),
}


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',  # OpenAPI sxema + Swagger UI (/api/docs/)
    'apps.catalog',
    'apps.payment',
    'apps.schedule',
    'apps.utils',
    'apps.booking',
    'apps.account',
    'apps.notifications',
    'apps.loadtest',
    # ⬇ Modeli yo'q (o'qish modeli Elasticsearch'da), lekin ro'yxatda
    # BO'LISHI SHART: Django management buyruqlarini faqat INSTALLED_APPS
    # ichidagi ilovalardan topadi. Busiz `manage.py reindex_doctors`
    # "Unknown command" beradi.
    'apps.search',
]
# 'rest_framework_simplejwt' pastda, _HAS_SIMPLEJWT sharti bilan qo'shiladi —
# paket o'rnatilmagan holatda Django umuman ishga tushmasligining oldini oladi.

MIDDLEWARE = [
    # E13: birinchi — keyingi hamma narsa (loglar, outbox hodisalari) shu ID'ni ko'radi
    'api.observability.correlation.CorrelationIdMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # A12: admin panel faqat ruxsat etilgan IP'lardan (boshqalarga 404)
    'api.admin_security.AdminIPRestrictionMiddleware',
    # Admin (jazzmin) static fayllari — gunicorn ortida alohida nginx kerak emas
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # C14: Accept-Language -> faol til; keyin bizning xabarlar tarjimasi
    'django.middleware.locale.LocaleMiddleware',
    'api.i18n.ApiTranslationMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # A11: audit yozuvi uchun actor va IP (api/audit.py)
    'api.audit.AuditContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# Format: "<app_label>.<ModelName>" — modul yo'li EMAS.
# 'apps.account' app'ining label'i oxirgi bo'lak, ya'ni "account".
AUTH_USER_MODEL = "account.User"
ROOT_URLCONF = 'conf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # A12: templates/admin/login.html — jazzmin login + 2FA maydoni
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'conf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  SQLite — faqat lokal qulaylik uchun. `POSTGRES_DB` berilsa PostgreSQL.   ║
# ║                                                                          ║
# ║  NEGA BU ALMASHTIRISH KERAK: SQLite bitta yozuvchiga mo'ljallangan.       ║
# ║  `apps/booking/tests.py` dagi 100 tomonli parallel bandlik testi          ║
# ║  SQLite'da "database table is locked" beradi — ya'ni loyihaning ASOSIY    ║
# ║  invariantini (bitta slotni faqat bittasi band qiladi) SQLite'da isbotlab ║
# ║  bo'lmaydi. Compare-and-set logikasi to'g'ri, lekin uni sinash uchun      ║
# ║  haqiqiy parallel yozishni ko'taradigan baza kerak.                       ║
# ║                                                                          ║
# ║  Ishga tushirish:                                                        ║
# ║    POSTGRES_DB=medbron POSTGRES_PASSWORD=... pytest                      ║
# ╚══════════════════════════════════════════════════════════════════════════╝
if env('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('POSTGRES_DB'),
            'USER': env('POSTGRES_USER', 'postgres'),
            'PASSWORD': env('POSTGRES_PASSWORD'),
            'HOST': env('POSTGRES_HOST', '127.0.0.1'),
            'PORT': env('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# C14: o'zbekcha default, ruscha — `Accept-Language: ru` yoki `?lang=ru` (api/i18n.py)
LANGUAGE_CODE = 'uz'
LANGUAGES = [('uz', "O'zbekcha"), ('ru', 'Русский')]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
# `collectstatic` shu yerga yig'adi (Dockerfile), WhiteNoise shu yerdan beradi
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    # Manifest (hash'li nomlar) faqat prodda: lokal/testlarda collectstatic
    # qilinmagan bo'lsa ham `{% static %}` yiqilmasin
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'
        if DEBUG
        else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    },
}

# D2: shifokor hujjatlari — MEDIA_URL orqali BERILMAYDI, faqat imzolangan havola
PRIVATE_MEDIA_ROOT = Path(env('PRIVATE_MEDIA_ROOT', str(BASE_DIR / 'private_media')))
PRIVATE_STORAGE_BACKEND = env('PRIVATE_STORAGE_BACKEND')  # prod: S3/MinIO backend
DOCUMENT_MAX_BYTES = int(env('DOCUMENT_MAX_BYTES', str(10 * 1024 * 1024)))
DOCUMENT_URL_TTL_SECONDS = int(env('DOCUMENT_URL_TTL_SECONDS', '300'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------

# simplejwt hali o'rnatilmagan bo'lishi mumkin (pip install djangorestframework-simplejwt).
# Shu tekshiruv bo'lmasa, paket yo'q holatda HAR BIR so'rov ImportError bilan
# yiqiladi. Paket o'rnatilishi bilan JWT avtomatik yoqiladi.
_HAS_SIMPLEJWT = find_spec("rest_framework_simplejwt") is not None

if _HAS_SIMPLEJWT:
    INSTALLED_APPS += [
        'rest_framework_simplejwt',
        # ROTATE_REFRESH_TOKENS + BLACKLIST_AFTER_ROTATION shu app'ni talab qiladi:
        # ishlatilgan refresh token qora ro'yxatga tushadi va qayta ishlatilmaydi.
        'rest_framework_simplejwt.token_blacklist',
    ]

REST_FRAMEWORK = {
    # Xato kodlarini BITTA joyda belgilaydigan handler (api/booking/utils.py).
    #   InvalidBookingRequest -> 400
    #   BookingError          -> 409 (slot band — klient boshqa vaqt tanlasin)
    'EXCEPTION_HANDLER': 'api.booking.utils.custom_exception_handler',

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'DEFAULT_AUTHENTICATION_CLASSES': (
        ['rest_framework_simplejwt.authentication.JWTAuthentication']
        if _HAS_SIMPLEJWT
        else []
    ),

    # Aniq ruxsat berilmagan endpoint yopiq bo'lsin — "default deny".
    # Ochiq endpoint'lar (katalog, slotlar) o'zida `permission_classes = []` yozadi,
    # ya'ni ochiqlik ATAYLAB va KO'RINADIGAN qaror bo'ladi, tasodif emas.
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],

    # A7: har bir yangi endpoint AVTOMATIK himoyalangan (api/throttling.py)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
        'api.throttling.WriteRateThrottle',
        'api.throttling.AnonReadThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'booking_create': env('THROTTLE_BOOKING_CREATE', '20/hour'),   # foydalanuvchi bo'yicha
        'booking_cancel': env('THROTTLE_BOOKING_CANCEL', '30/hour'),
        'sensitive': env('THROTTLE_SENSITIVE', '5/hour'),              # akkaunt o'chirish va h.k.
        'write': env('THROTTLE_WRITE', '60/hour'),                     # boshqa POST/PUT/PATCH/DELETE
        'anon_read': env('THROTTLE_ANON_READ', '300/hour'),            # katalog, IP bo'yicha
        # OTP endpoint'lari IP bo'yicha shu limitda. Bu api/account/services.py
        # dagi telefon bo'yicha cheklovning O'RNIGA emas, USTIGA qo'shiladi:
        # throttle tez va arzon (kesh), services.py dagi tekshiruv aniqroq.
        'otp': env('THROTTLE_OTP', '10/hour'),
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'MedBron API',
    'DESCRIPTION': (
        "Tibbiy xizmatlarni bron qilish platformasi.\n\n"
        "**Autentifikatsiya:** `POST /api/v1/accounts/auth/otp/request` → kod "
        "(lokalda runserver terminalida) → `POST /api/v1/accounts/auth/otp/verify` → "
        "`tokens.access` ni yuqoridagi **Authorize** tugmasiga kiriting."
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SWAGGER_UI_SETTINGS': {'persistAuthorization': True},
}

# Swagger faqat lokalda default yoqiq. Prodda API tuzilmasini ochiq
# e'lon qilmaslik uchun o'chiq — kerak bo'lsa SWAGGER_ENABLED=1.
SWAGGER_ENABLED = env('SWAGGER_ENABLED', '1' if DEBUG else '0') == '1'

SIMPLE_JWT = {
    # access qisqa muddatli: o'g'irlansa tez eskiradi
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    # refresh uzoq muddatli, lekin kamdan-kam uzatiladi -> ushlab olish ehtimoli past
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': env('JWT_SIGNING_KEY', SECRET_KEY),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}


# ---------------------------------------------------------------------------
# Kesh (api/schedule/cache.py)
# ---------------------------------------------------------------------------

# Lokal ishlab chiqishda LocMemCache yetarli va hech narsa o'rnatish shart emas.
# ⚠️ LEKIN u HAR PROTSESSDA ALOHIDA: bir necha worker/pod bo'lganda ular
# bir-birining keshini ko'rmaydi va `invalidate_doctor_day` faqat o'z
# protsessida ishlaydi. Shuning uchun prodda Redis MAJBURIY.
if env('REDIS_URL'):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': env('REDIS_URL'),  # redis://redis:6379/1
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'medbron-dev',
        }
    }


# ---------------------------------------------------------------------------
# Tashqi servislar
# ---------------------------------------------------------------------------

# Kafka — api/events/publisher.py, api/notifications/consumer.py,
# api/search/projector.py, analytics/consumer.py
KAFKA_BOOTSTRAP_SERVERS = env('KAFKA_BOOTSTRAP_SERVERS', 'localhost:9092')

# Bildirishnoma servisi (gRPC) — api/notifications/klient.py
NOTIFICATION_GRPC_ADDR = env('NOTIFICATION_GRPC_ADDR', 'localhost:50051')

# Elasticsearch — api/search/*
ELASTICSEARCH_URL = env('ELASTICSEARCH_URL', 'http://localhost:9200')

# ClickHouse — analytics/*
CLICKHOUSE_HOST = env('CLICKHOUSE_HOST', 'localhost')

# OpenTelemetry kollektori — api/observability/tracing.py
# BO'SH QOLDIRILSA TRACING O'CHIQ. Bu ataylab: default'i qattiq yozilgan
# bo'lsa, lokalda va testlarda mavjud bo'lmagan hostga urinib stderr'ni
# ogohlantirishlar bilan to'ldiradi.
OTEL_EXPORTER_OTLP_ENDPOINT = env('OTEL_EXPORTER_OTLP_ENDPOINT')


# ---------------------------------------------------------------------------
# To'lov provayderlari — api/payments/*
# ---------------------------------------------------------------------------

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  PAYME_SECRET_KEY — webhook imzosini tekshirish kaliti.                  ║
# ║  Bu kalit noto'g'ri yoki bo'sh bo'lsa, verify_payme_signature() har      ║
# ║  so'rovni RAD ETADI — bu xavfsiz nosozlik (fail-closed). Teskarisi       ║
# ║  falokat bo'lardi: hujumchi PerformTransaction yuborib, PUL TO'LAMASDAN  ║
# ║  bronni tasdiqlatib olardi.                                              ║
# ║                                                                          ║
# ║  Shuning uchun bu yerda default YO'Q — qiymat faqat muhitdan keladi.     ║
# ╚══════════════════════════════════════════════════════════════════════════╝
PAYME_SECRET_KEY = env('PAYME_SECRET_KEY')
PAYME_MERCHANT_ID = env('PAYME_MERCHANT_ID')
PAYME_CHECKOUT_URL = env('PAYME_CHECKOUT_URL', 'https://checkout.paycom.uz')
# A8: Payme serverlari IP'lari (vergul bilan). Bo'sh — tekshiruv o'chiq (lokal).
PAYME_ALLOWED_IPS = [ip.strip() for ip in env('PAYME_ALLOWED_IPS').split(',') if ip.strip()]
PAYME_MAX_BODY_BYTES = int(env('PAYME_MAX_BODY_BYTES', '65536'))
CLICK_MERCHANT_ID = env('CLICK_MERCHANT_ID')
CLICK_SERVICE_ID = env('CLICK_SERVICE_ID')
# B6: SHOP API imzo kaliti (default YO'Q — bo'sh bo'lsa webhook fail-closed)
CLICK_SECRET_KEY = env('CLICK_SECRET_KEY')
# Merchant API (refund / reversal) uchun
CLICK_MERCHANT_USER_ID = env('CLICK_MERCHANT_USER_ID')
CLICK_API_URL = env('CLICK_API_URL', 'https://api.click.uz/v2/merchant')
# Click serverlari IP'lari (vergul bilan). Bo'sh — tekshiruv o'chiq (lokal).
CLICK_ALLOWED_IPS = [ip.strip() for ip in env('CLICK_ALLOWED_IPS').split(',') if ip.strip()]

# B8: pul taqsimoti. Stavkalar bron paytida muzlatiladi (Booking.commission_rate).
PLATFORM_COMMISSION_RATE = env('PLATFORM_COMMISSION_RATE', '0.15')
PROVIDER_FEE_RATES = {
    'payme': env('PAYME_FEE_RATE', '0.01'),
    'click': env('CLICK_FEE_RATE', '0.01'),
}

# B12: fiskal chek default rekvizitlari. ⚠️ Aniq MXIK kodi, o'lchov birligi va
# QQS stavkasini soliq maslahatchisi bilan tasdiqlang (tibbiy xizmatlar QQS'dan
# ozod bo'lishi mumkin — shuning uchun default 0).
FISCAL = {
    'default_mxik_code': env('FISCAL_DEFAULT_MXIK', ''),
    'default_package_code': env('FISCAL_DEFAULT_PACKAGE_CODE', ''),
    'default_vat_percent': int(env('FISCAL_DEFAULT_VAT_PERCENT', '0')),
    'tin': env('FISCAL_TIN', ''),  # platforma STIR (INN)
}

# C12: chegirmalar (api/booking/discounts.py). 0 = o'chiq.
PRICING = {
    'first_booking_percent': int(env('FIRST_BOOKING_DISCOUNT_PERCENT', '0')),
}

# D6: haftalik payout — shu summadan kam bo'lsa keyingi haftaga o'tadi
PAYOUT_MIN_AMOUNT = env('PAYOUT_MIN_AMOUNT', '50000')

# D11: Telegram bot (shifokorlar uchun). Token bo'sh bo'lsa bot o'chiq.
TELEGRAM_BOT_TOKEN = env('TELEGRAM_BOT_TOKEN')
TELEGRAM_BOT_USERNAME = env('TELEGRAM_BOT_USERNAME', 'medbron_doctor_bot')
TELEGRAM_WEBHOOK_SECRET = env('TELEGRAM_WEBHOOK_SECRET')

# C2: bekor qilish siyosati (api/booking/cancellation.py). Biznes tasdiqlashi kerak.
CANCELLATION_POLICY = {
    'full_refund_hours': int(env('CANCEL_FULL_REFUND_HOURS', '24')),
    'partial_refund_hours': int(env('CANCEL_PARTIAL_REFUND_HOURS', '2')),
    'partial_refund_percent': int(env('CANCEL_PARTIAL_REFUND_PERCENT', '50')),
}

# B10: to'lov rejimlari. `deposit_percent` — zaklad foizi, qolgani
# klinikada to'lanadi. `force_prepaid_after_no_shows` — shuncha marta
# kelmagan mijoz uchun rejim majburan `prepaid` ga tushadi (no-show riskini
# aynan shu mijozlar keltiradi).
PAYMENT_MODES = {
    'deposit_percent': int(env('DEPOSIT_PERCENT', '20')),
    'force_prepaid_after_no_shows': int(env('FORCE_PREPAID_AFTER_NO_SHOWS', '2')),
}

# C9: eslatmalar (api/notifications/scheduler.py). Qabulgacha necha soat
# qolganda yuboriladi; `review_after_hours` — qabul tugagandan keyin.
# 0 yoki bo'sh qiymat -> o'sha eslatma butunlay o'chadi.
BOOKING_REMINDERS = {
    'first_hours': int(env('REMINDER_FIRST_HOURS', '24')),
    'second_hours': int(env('REMINDER_SECOND_HOURS', '2')),
    'review_after_hours': int(env('REVIEW_REQUEST_AFTER_HOURS', '2')),
}

# Prodda bu sozlamasiz ishga tushish — jimgina to'lovni buzish demak.
_require_in_prod('PAYME_SECRET_KEY')


# ---------------------------------------------------------------------------
# SMS — api/notifications/sms.py
# ---------------------------------------------------------------------------

# console = faqat logga (lokal), eskiz = notify.eskiz.uz.
# Berilmasa: DEBUG da console, prodda eskiz.
SMS_PROVIDER = env('SMS_PROVIDER') or ('console' if DEBUG else 'eskiz')
ESKIZ_BASE_URL = env('ESKIZ_BASE_URL', 'https://notify.eskiz.uz')
ESKIZ_EMAIL = env('ESKIZ_EMAIL')
ESKIZ_PASSWORD = env('ESKIZ_PASSWORD')
ESKIZ_FROM = env('ESKIZ_FROM', '4546')  # Eskiz kabinetidagi jo'natuvchi nomi

# C13: mobil push. console — logga (lokal), fcm — Firebase (google-auth kerak), off — o'chiq.
PUSH_PROVIDER = env('PUSH_PROVIDER') or ('console' if DEBUG else 'off')
FCM_PROJECT_ID = env('FCM_PROJECT_ID')
FCM_CREDENTIALS_FILE = env('FCM_CREDENTIALS_FILE')

if SMS_PROVIDER == 'eskiz' and not (ESKIZ_EMAIL and ESKIZ_PASSWORD):
    raise ImproperlyConfigured("SMS_PROVIDER=eskiz uchun ESKIZ_EMAIL va ESKIZ_PASSWORD kerak")
if not DEBUG and SMS_PROVIDER == 'console':
    raise ImproperlyConfigured("Prodda SMS_PROVIDER=console bo'lishi mumkin emas — SMS hech kimga ketmaydi")

# ---------------------------------------------------------------------------
# A12: Django admin himoyasi (api/admin_security.py)
# ---------------------------------------------------------------------------

# Prodda tasodifiy prefiks majburiy — `admin/` skanerlar ro'yxatida birinchi
ADMIN_URL = env('ADMIN_URL', 'admin/').strip('/') + '/'
if not DEBUG and ADMIN_URL == 'admin/':
    raise ImproperlyConfigured("Prodda ADMIN_URL tasodifiy bo'lishi kerak (masalan 'ops-7f3k2/')")
# Ofis / VPN tarmoqlari (CIDR, vergul bilan). Bo'sh — cheklov yo'q (faqat lokal).
ADMIN_ALLOWED_IPS = [ip.strip() for ip in env('ADMIN_ALLOWED_IPS').split(',') if ip.strip()]
ADMIN_2FA_REQUIRED = env('ADMIN_2FA_REQUIRED', '0' if DEBUG else '1') == '1'
if not DEBUG and not ADMIN_ALLOWED_IPS:
    raise ImproperlyConfigured("Prodda ADMIN_ALLOWED_IPS majburiy (admin panel faqat VPN/ofisdan)")

# Sessiya faqat admin panelda ishlatiladi (API — JWT)
SESSION_COOKIE_AGE = 30 * 60
SESSION_SAVE_EVERY_REQUEST = True   # 30 daqiqa — FAOLSIZLIKDAN keyin
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SAMESITE = 'Strict'
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'


# ---------------------------------------------------------------------------
# A13: transport va brauzer xavfsizligi. `manage.py check --deploy` CI'da.
# ---------------------------------------------------------------------------

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'

if not DEBUG:
    # Ilova TLS terminatsiya qiluvchi proxy/Ingress ortida turadi
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = env('SECURE_SSL_REDIRECT', '1') == '1'
    # Probe'lar ichki HTTP bilan keladi — ularni HTTPS'ga yo'naltirmaymiz
    SECURE_REDIRECT_EXEMPT = [r'^healthz/']
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    if '*' in ALLOWED_HOSTS:
        raise ImproperlyConfigured("Prodda ALLOWED_HOSTS='*' taqiqlangan")

# CORS: API mobil ilova uchun — brauzer origin'lari kerak emas, shuning uchun
# `django-cors-headers` ATAYLAB o'rnatilmagan (CORS sarlavhasi yo'q = brauzerdan
# begona sayt so'rov o'qiy olmaydi). Veb-klient paydo bo'lsa — aniq origin ro'yxati.


# E13: strukturali JSON loglar + correlation_id. LOG_FORMAT=text — lokalda o'qish uchun.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'correlation': {'()': 'api.observability.correlation.CorrelationIdFilter'},
    },
    'formatters': {
        'json': {'()': 'api.observability.correlation.JsonFormatter'},
        'text': {'format': '%(asctime)s %(levelname)s [%(correlation_id)s] %(name)s: %(message)s'},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'filters': ['correlation'],
            'formatter': env('LOG_FORMAT', 'text' if DEBUG else 'json'),
        },
    },
    'root': {'handlers': ['console'], 'level': env('LOG_LEVEL', 'INFO')},
}

TIMEOUT_SECONDS = 2.0  # SMS 2 soniyada ketmasa, mijozni kuttirmaymiz
MAX_ATTEMPTS = 3
BASE_BACKOFF = 0.1

import grpc
# Faqat shu kodlarda qayta urinamiz.
# INVALID_ARGUMENT yoki NOT_FOUND da qayta urinish mantiqsiz — so'rov
# o'zi noto'g'ri, yuz marta yuborsangiz ham natija o'zgarmaydi.
RETRYABLE = {
    grpc.StatusCode.UNAVAILABLE,
    grpc.StatusCode.DEADLINE_EXCEEDED,
    grpc.StatusCode.RESOURCE_EXHAUSTED,
}


class NotificationUnavailable(Exception):
    """Servis mavjud emas. Chaqiruvchi buni YUTISHI kerak."""

