# Generated by Django 6.0.7 on 2026-07-29 05:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='catalog.doctor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('doctor', 'date'), name='uniq_doctor_exception_date')],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('free', "Bo'sh"), ('held', 'Vaqtincha band'), ('booked', 'Band'), ('blocked', 'Yopilgan')], default='free', max_length=10)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='catalog.doctor')),
            ],
            options={
                'indexes': [models.Index(fields=['doctor', 'status', 'start_at'], name='schedule_ti_doctor__caab43_idx'), models.Index(fields=['clinic', 'status', 'start_at'], name='schedule_ti_clinic__23957d_idx')],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'start_at'), name='uniq_doctor_slot_start'), models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='slot_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='WorkingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_minutes', models.PositiveSmallIntegerField(default=30)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_rules', to='catalog.doctor')),
            ],
            options={
                'indexes': [models.Index(fields=['doctor', 'weekday'], name='schedule_wo_doctor__12b74f_idx')],
            },
        ),
    ]
