# Generated by Django 6.0.7 on 2026-09-15 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_doctor_education_doctor_languages_and_more'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='block_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='block_reason',
            field=models.CharField(blank=True, choices=[('', '—'), ('travel_buffer', "Uy chaqiruvi yo'l vaqti"), ('time_off', "Ta'til / dam olish"), ('manual', 'Shifokor yopdi')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('kind', models.CharField(choices=[('vacation', "Ta'til"), ('sick', 'Kasallik'), ('personal', 'Shaxsiy'), ('other', 'Boshqa')], default='other', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to='catalog.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='timeslot',
            name='time_off',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='schedule.timeoff'),
        ),
        migrations.AddIndex(
            model_name='timeoff',
            index=models.Index(fields=['doctor', 'start_at', 'end_at'], name='schedule_ti_doctor__a0d130_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeoff',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='time_off_end_after_start'),
        ),
    ]
