# Generated by Django 6.0.7 on 2026-09-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_timeslot_block_note_timeslot_block_reason_timeoff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='travel_buffer_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
