# Generated by Django 6.0.7 on 2026-09-18 06:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_b2b'),
        ('schedule', '0003_timeslot_travel_buffer_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicClosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='timeslot',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='catalog.room'),
        ),
        migrations.AddField(
            model_name='workingrule',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.room'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='block_reason',
            field=models.CharField(blank=True, choices=[('', '—'), ('travel_buffer', "Uy chaqiruvi yo'l vaqti"), ('time_off', "Ta'til / dam olish"), ('manual', 'Shifokor yopdi'), ('clinic_closed', 'Klinika yopiq')], default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('room', 'start_at'), name='uniq_room_slot_start'),
        ),
        migrations.AddField(
            model_name='clinicclosure',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='catalog.clinic'),
        ),
        migrations.AddConstraint(
            model_name='clinicclosure',
            constraint=models.UniqueConstraint(fields=('clinic', 'date'), name='uniq_clinic_closure_date'),
        ),
    ]
