# Generated by Django 6.0.7 on 2026-09-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_managers_user_groups_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
