# Generated by Django 6.0.7 on 2026-07-29 05:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('catalog', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending_payment', "To'lov kutilmoqda"), ('confirmed', 'Tasdiqlangan'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan'), ('expired', "Muddati o'tgan"), ('no_show', 'Kelmadi')], default='pending_payment', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('client_comment', models.TextField(blank=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.address')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='account.user')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.patient')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='schedule.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', '-created_at'], name='booking_boo_client__09f254_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['doctor', 'status'], name='booking_boo_doctor__f5ef98_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='booking_boo_status_4662db_idx'),
        ),
    ]
