# Generated by Django 6.0.7 on 2026-09-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_request_hash_alter_booking_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='completed_by',
            field=models.CharField(blank=True, choices=[('client', 'Mijoz'), ('doctor', 'Shifokor'), ('admin', 'Admin'), ('system', 'Tizim')], max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='no_show_by',
            field=models.CharField(blank=True, choices=[('client', 'Mijoz'), ('doctor', 'Shifokor'), ('admin', 'Admin'), ('system', 'Tizim')], max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
