# Generated by Django 6.0.7 on 2026-09-15 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_completed_at_booking_completed_by_and_more'),
        ('payment', '0003_providerrequestlog_alter_payment_status_refund'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='doctor_payout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_fee_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('doctor_no_show', 'Shifokor kelmadi'), ('poor_service', 'Xizmat sifatsiz'), ('wrong_charge', "Noto'g'ri summa yechildi"), ('other', 'Boshqa')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('resolved_client', 'Mijoz foydasiga'), ('resolved_doctor', 'Shifokor foydasiga')], default='open', max_length=20)),
                ('due_at', models.DateTimeField()),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='booking.booking')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to=settings.AUTH_USER_MODEL)),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.refund')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'due_at'], name='booking_dis_status_899f2d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('booking',), name='uniq_open_dispute_per_booking')],
            },
        ),
    ]
