# Generated by Django 6.0.7 on 2026-09-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_commission_rate_booking_doctor_payout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
