# Generated by Django 6.0.7 on 2026-09-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rescheduled_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
