# Generated by Django 6.0.7 on 2026-09-18 03:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_rescheduled_count'),
        ('catalog', '0004_doctor_telegram_chat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('place', models.CharField(choices=[('clinic', 'Klinikada'), ('home', 'Uyda')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Kutmoqda'), ('notified', 'Xabar berildi'), ('converted', 'Bronga aylandi'), ('cancelled', 'Bekor qilindi'), ('expired', "Muddati o'tdi")], default='active', max_length=10)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('notified_count', models.PositiveSmallIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='catalog.doctor')),
            ],
            options={
                'indexes': [models.Index(fields=['doctor', 'status', 'created_at'], name='booking_wai_doctor__dbbe0d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'notified'])), fields=('client', 'doctor'), name='uniq_active_waitlist_per_doctor')],
            },
        ),
    ]
