# Generated by Django 6.0.7 on 2026-09-18 03:51

from django.db import migrations, models
from django.db.models import F


def backfill_prepay_amount(apps, schema_editor):
    """Mavjud bronlarning hammasi `prepaid` edi — onlayn summa = to'liq narx.

    Busiz eski bronlar `prepay_amount=0` bilan qolar va `create_checkout`
    ularni "klinikada to'lanadi" deb rad etardi: to'lanmagan bronlar
    to'lab bo'lmaydigan holatga tushib qolardi."""
    apps.get_model("booking", "Booking").objects.update(prepay_amount=F("total_price"))


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('prepaid', "To'liq oldindan"), ('deposit', 'Zaklad'), ('at_clinic', "Klinikada to'lanadi")], default='prepaid', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='prepay_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(backfill_prepay_amount, migrations.RunPython.noop),
    ]
