# Generated by Django 6.0.7 on 2026-09-18 04:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_payment_mode_booking_prepay_amount'),
        ('catalog', '0006_doctor_home_base_latitude_doctor_home_base_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('published', "E'lon qilingan"), ('pending', 'Moderatsiyada'), ('rejected', 'Rad etilgan')], default='published', max_length=10)),
                ('moderation_flags', models.JSONField(blank=True, default=list)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_reply', models.TextField(blank=True)),
                ('doctor_replied_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='booking.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='catalog.doctor')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['doctor', 'status', '-created_at'], name='booking_rev_doctor__02c966_idx'), models.Index(fields=['status', 'created_at'], name='booking_rev_status_5f6440_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_1_5')],
            },
        ),
    ]
