# Generated by Django 6.0.7 on 2026-09-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='mxik_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='package_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='vat_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
