# Generated by Django 6.0.7 on 2026-09-22 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_pricing_discounts'),
        ('catalog', '0011_pricerule_servicepackage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_adjust_percent',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PackageEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sessions_total', models.PositiveSmallIntegerField()),
                ('discount_percent', models.PositiveSmallIntegerField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_enrollments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.doctor')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='catalog.servicepackage')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.service')),
            ],
        ),
        migrations.CreateModel(
            name='PackageUse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package_use', to='booking.booking')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='booking.packageenrollment')),
            ],
        ),
        migrations.AddIndex(
            model_name='packageenrollment',
            index=models.Index(fields=['client', 'service', 'is_active'], name='booking_pac_client__1bdaf5_idx'),
        ),
        migrations.AddConstraint(
            model_name='packageenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('client', 'service'), name='uniq_active_package_per_service'),
        ),
        migrations.AddIndex(
            model_name='packageuse',
            index=models.Index(fields=['enrollment', 'is_active'], name='booking_pac_enrollm_580f9b_idx'),
        ),
    ]
