# Generated by Django 6.0.7 on 2026-07-29 05:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_pediatric', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('pending', 'Moderatsiyada'), ('active', 'Faol'), ('suspended', "To'xtatilgan")], default='draft', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'city'], name='catalog_cli_status_a72c57_idx'), models.Index(fields=['latitude', 'longitude'], name='catalog_cli_latitud_8e8148_idx')],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Moderatsiyada'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('suspended', "To'xtatilgan")], default='pending', max_length=20)),
                ('accepts_home_visits', models.BooleanField(default=False)),
                ('home_visit_radius_km', models.PositiveSmallIntegerField(default=10)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profile', to='account.user')),
                ('specializations', models.ManyToManyField(related_name='doctors', to='catalog.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAffiliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='catalog.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='catalog.doctor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('doctor', 'clinic'), name='uniq_doctor_clinic')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('place', models.CharField(choices=[('clinic', 'Klinikada'), ('home', 'Uyda')], max_length=10)),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalog.clinic')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalog.doctor')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.specialization')),
            ],
            options={
                'indexes': [models.Index(fields=['specialization', 'place', 'is_active'], name='catalog_ser_special_cea69e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('clinic__isnull', False), ('doctor__isnull', False), _connector='OR'), name='service_has_owner')],
            },
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['status', 'accepts_home_visits'], name='catalog_doc_status_a58238_idx'),
        ),
    ]
