# Generated by Django 6.0.7 on 2026-09-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_servicepricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
