# Generated by Django 6.0.7 on 2026-09-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_doctor_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic_payment_mode',
            field=models.CharField(choices=[('prepaid', "To'liq oldindan"), ('deposit', 'Zaklad'), ('at_clinic', 'Klinikada')], default='prepaid', max_length=10),
        ),
    ]
