# Generated by Django 6.0.7 on 2026-09-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_doctor_clinic_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='home_base_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='home_base_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='accepts_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialization',
            name='allowed_gender',
            field=models.CharField(blank=True, choices=[('', 'Hammasi'), ('male', 'Erkak'), ('female', 'Ayol')], max_length=10),
        ),
        migrations.AddField(
            model_name='specialization',
            name='max_patient_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='min_patient_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
