# Generated by Django 6.0.7 on 2026-09-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_doctor_home_base_latitude_doctor_home_base_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='mxik_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='service',
            name='package_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='service',
            name='vat_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
