# Generated by Django 6.0.7 on 2026-09-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_fiscal_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='follow_up_discount_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
