# Generated by Django 6.0.7 on 2026-09-18 06:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def _backfill_status(apps, schema_editor):
    # D7: eski faol bo'lmagan affiliatsiyalar — "tugatilgan"
    Aff = apps.get_model("catalog", "DoctorAffiliation")
    Aff.objects.filter(is_active=False).update(status="ended")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_pricing_discounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='doctoraffiliation',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctoraffiliation',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoraffiliation',
            name='status',
            field=models.CharField(choices=[('invited', 'Taklif yuborilgan'), ('active', 'Faol'), ('paused', "To'xtatilgan"), ('declined', 'Rad etilgan'), ('ended', 'Tugatilgan')], default='active', max_length=10),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='catalog.clinic')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('clinic', 'name'), name='uniq_room_name_per_clinic')],
            },
        ),
        migrations.RunPython(_backfill_status, migrations.RunPython.noop),
    ]
