# Generated by Django 6.0.7 on 2026-09-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_b2b'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='specialization',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
