# Generated by Django 6.0.7 on 2026-09-22 10:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_i18n_channels'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('weekdays', models.CharField(blank=True, max_length=7)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('percent', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(100)])),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='catalog.doctor')),
            ],
            options={
                'indexes': [models.Index(fields=['doctor', 'is_active', 'priority'], name='catalog_pri_doctor__cb643e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('sessions', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('discount_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('validity_days', models.PositiveSmallIntegerField(default=90)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='catalog.doctor')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='catalog.service')),
            ],
            options={
                'indexes': [models.Index(fields=['doctor', 'is_active'], name='catalog_ser_doctor__a6ed1f_idx')],
            },
        ),
    ]
