# Generated by Django 6.0.7 on 2026-07-29 05:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('cash', 'Naqd')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('created', 'Yaratilgan'), ('processing', 'Jarayonda'), ('succeeded', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz'), ('refunded', 'Qaytarilgan')], default='created', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='booking.booking')),
            ],
            options={
                'indexes': [models.Index(fields=['booking', 'status'], name='payment_pay_booking_8db1ab_idx'), models.Index(fields=['provider', 'external_id'], name='payment_pay_provide_7e4122_idx')],
            },
        ),
    ]
