# Generated by Django 6.0.7 on 2026-09-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_request_hash_alter_booking_idempotency_key_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeCallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, max_length=64)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='cancel_reason',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cancel_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='needs_refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='perform_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_create_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Yaratilgan'), ('processing', 'Jarayonda'), ('succeeded', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz'), ('cancelled', 'Bekor qilingan'), ('expired', "Muddati o'tgan"), ('refunded', 'Qaytarilgan')], default='created', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'provider_create_time'], name='payment_pay_provide_f7b12c_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'succeeded')), fields=('booking',), name='uniq_succeeded_payment_per_booking'),
        ),
        migrations.AddIndex(
            model_name='paymecallbacklog',
            index=models.Index(fields=['method', '-created_at'], name='payment_pay_method_94a1cf_idx'),
        ),
    ]
