# Generated by Django 6.0.7 on 2026-09-15 10:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_completed_at_booking_completed_by_and_more'),
        ('payment', '0002_paymecallbacklog_payment_cancel_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('operation', models.CharField(max_length=64)),
                ('request', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Yaratilgan'), ('processing', 'Jarayonda'), ('succeeded', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz'), ('cancelled', 'Bekor qilingan'), ('expired', "Muddati o'tgan"), ('refunded', 'Qaytarilgan'), ('partially_refunded', 'Qisman qaytarilgan')], default='created', max_length=20),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('succeeded', 'Qaytarildi'), ('failed', "Xato (qo'lda ko'rish kerak)"), ('manual_required', "Qo'lda qaytarish kerak")], default='pending', max_length=20)),
                ('initiated_by', models.CharField(choices=[('client', 'Mijoz'), ('doctor', 'Shifokor'), ('admin', 'Admin'), ('system', 'Tizim')], max_length=10)),
                ('external_refund_id', models.CharField(blank=True, max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='booking.booking')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payment.payment')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='payment_ref_status_2f0e0c_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking', 'reason'), name='uniq_refund_booking_reason'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive')],
            },
        ),
    ]
