# Generated by Django 6.0.7 on 2026-09-15 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_commission_rate_booking_doctor_payout_and_more'),
        ('catalog', '0001_initial'),
        ('payment', '0003_providerrequestlog_alter_payment_status_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=40)),
                ('ref_type', models.CharField(max_length=20)),
                ('ref_id', models.UUIDField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transactions', to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('client_payments', 'Mijozlardan tushum (provayderda)'), ('platform_revenue', 'Platforma daromadi'), ('doctor_payable', 'Shifokorlarga qarz'), ('provider_fees', 'Provayder komissiyasi')], max_length=30)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.doctor')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='payment.ledgertransaction')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDiscrepancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('provider_only', "Provayderda bor, bizda yo'q (pul olindi, xizmat yo'q)"), ('local_only', "Bizda succeeded, provayderda yo'q"), ('amount_mismatch', 'Summa farq qiladi'), ('status_mismatch', 'Holat farq qiladi'), ('missing_ledger', "To'lov daftarga tushmagan"), ('booking_without_payment', "Tasdiqlangan bron, to'lov yo'q"), ('unresolved_refund', 'Refund kerak, lekin yaratilmagan'), ('ledger_imbalance', 'Daftar balansi 0 emas')], max_length=30)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('local_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('provider_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('period_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('resolved', 'Hal qilingan')], default='open', max_length=10)),
                ('resolution_note', models.TextField(blank=True)),
                ('fingerprint', models.CharField(max_length=255)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.booking')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.payment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ledgertransaction',
            constraint=models.UniqueConstraint(fields=('kind', 'ref_id'), name='uniq_ledger_kind_ref'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'doctor'], name='payment_led_account_be0b12_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0), models.Q(('debit', 0), ('credit', 0), _connector='OR')), name='ledger_entry_one_side_non_negative'),
        ),
        migrations.AddIndex(
            model_name='paymentdiscrepancy',
            index=models.Index(fields=['status', 'type'], name='payment_pay_status_8eab18_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentdiscrepancy',
            constraint=models.UniqueConstraint(fields=('fingerprint', 'period_date'), name='uniq_discrepancy_per_period'),
        ),
    ]
