# Generated by Django 6.0.7 on 2026-09-15 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_started_at'),
        ('catalog', '0004_doctor_telegram_chat_id'),
        ('payment', '0004_ledgertransaction_ledgerentry_paymentdiscrepancy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='account',
            field=models.CharField(choices=[('client_payments', 'Mijozlardan tushum (provayderda / bankda)'), ('platform_revenue', 'Platforma daromadi'), ('doctor_payable', 'Shifokorlarga qarz'), ('provider_fees', 'Provayder komissiyasi')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transactions', to='booking.booking'),
        ),
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holder_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(max_length=34)),
                ('mfo', models.CharField(blank=True, max_length=10)),
                ('inn', models.CharField(blank=True, max_length=14)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_account', to='catalog.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayoutPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', "To'lanishi kutilmoqda"), ('paid', "To'langan")], default='pending', max_length=10)),
                ('bookings_count', models.PositiveIntegerField(default=0)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('provider_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('refunds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('bank_reference', models.CharField(blank=True, max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='catalog.doctor')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refunds_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout_line', to='booking.booking')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payment.payoutperiod')),
            ],
        ),
        migrations.AddIndex(
            model_name='payoutperiod',
            index=models.Index(fields=['status', 'period_end'], name='payment_pay_status_47117f_idx'),
        ),
        migrations.AddConstraint(
            model_name='payoutperiod',
            constraint=models.UniqueConstraint(fields=('doctor', 'period_start', 'period_end'), name='uniq_payout_period'),
        ),
    ]
