# Generated by Django 6.0.7 on 2026-09-18 03:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_started_at'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('reminder_24h', 'Eslatma — 24 soat oldin'), ('reminder_2h', 'Eslatma — 2 soat oldin'), ('review_request', "Baholash so'rovi")], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('params', models.JSONField(default=dict)),
                ('language', models.CharField(default='uz', max_length=2)),
                ('send_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Navbatda'), ('sent', 'Yuborildi'), ('cancelled', 'Bekor qilindi'), ('skipped', "O'tkazib yuborildi")], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_notifications', to='booking.booking')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'send_at'], name='notificatio_status_48f713_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking', 'kind'), name='uniq_scheduled_notification')],
            },
        ),
    ]
